// frontend/assemble.mjs
// Assembles the mockup .jsx files (which use global functions + window.CFData,
// CDN-style) into a single Vite-compatible module: src/CyberFusionApp.jsx.
//
// Transformations:
//   • prepend React hook imports
//   • strip the mockup's ReactDOM.createRoot bootstrap (Vite's main.jsx does it)
//   • strip the TweaksPanel design-editor block (not needed in the real app)
//   • leave window.CFData references intact — a runtime shim provides it from the API
//
// Run:  node assemble.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const M = join(process.cwd(), "src", "mockup");
const read = (p) => readFileSync(join(M, p), "utf8");

// Dependency order: components → pages → app
const parts = [
  read("cf_api.jsx"),
  read("components.jsx"),
  read("pages/onboarding.jsx"),
  read("pages/sources.jsx"),
  read("pages/executive.jsx"),
  read("pages/findings.jsx"),
  read("pages/detail.jsx"),
  read("pages/feed.jsx"),
  read("pages/exposure.jsx"),
  read("pages/briefing.jsx"),
  read("pages/methodology.jsx"),
  read("app.jsx"),
];

let body = parts.join("\n\n/* ===== next module ===== */\n\n");

// 0) Strip CDN-style React-hook destructuring; we import hooks instead.
body = body.replace(/const\s*\{[^}]*\}\s*=\s*React;?/g, "");

// 1) Remove the mockup's own ReactDOM bootstrap (Vite main.jsx handles mounting).
//    Strip from the "// Apply density tweak" comment through the createRoot call.
body = body.replace(/\/\/ Apply density tweak[\s\S]*$/m, "");
// Belt-and-suspenders: remove any remaining ReactDOM.createRoot(...).render(...) call.
body = body.replace(/ReactDOM\.createRoot[\s\S]*?\);?\s*$/m, "");
// Remove stray DOM bootstrap helpers that assume CDN globals.
body = body.replace(/const styleEl = document\.createElement[\s\S]*?dataset\.sidebar = "dark";/m, "");

// 2) Strip the TweaksPanel editor block from app.jsx (brace-matched).
const marker = 'typeof TweaksPanel !== "undefined"';
const mi = body.indexOf(marker);
if (mi !== -1) {
  const start = body.lastIndexOf("{", mi);
  let depth = 0, j = start;
  for (; j < body.length; j++) {
    if (body[j] === "{") depth++;
    else if (body[j] === "}") { depth--; if (depth === 0) break; }
  }
  body = body.slice(0, start) + "{/* tweaks panel removed for production app */}" + body.slice(j + 1);
}
// Remove the useTweaks fallback line + tweak effect hooks that depend on it.
body = body.replace(/const \[t, setTweak\][\s\S]*?\}, \[t\.darkSidebar\]\);/m,
  "const t = { accent: \"#0FB5A8\", density: \"comfortable\", darkSidebar: true, showPeerBenchmark: true };\n  const setTweak = () => {};");

// 3a) Add routes for the two new interactive pages in the App switch.
body = body.replace(
  '{page === "executive" && <ExecutiveView onOpenFinding={openFinding} onNav={onNav} />}',
  '{page === "executive" && <ExecutiveView onOpenFinding={openFinding} onNav={onNav} />}\n        {page === "sources" && <SourcesPage />}'
);

// 3b) Export the App component so main.jsx can import it.
body = body.replace(/const App = \(\) => \{/, "export const App = () => {");

// 4) Prepend imports + a thin window.CFData shim note.
const header = `// AUTO-GENERATED by assemble.mjs — do not edit directly.
// Source: src/mockup/*.jsx (the design mockup), wired to live API data.
import React, { useState, useEffect, useRef, useMemo, useCallback } from "react";
import "./mockup/styles.css";

// window.CFData is populated by main.jsx (fetched from the API) BEFORE <App/>
// renders, so the mockup code that reads window.CFData works unchanged.

`;

writeFileSync(join(process.cwd(), "src", "CyberFusionApp.jsx"), header + body, "utf8");
console.log("✓ wrote src/CyberFusionApp.jsx (" + (header + body).length + " bytes)");
